FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src/
COPY ["./merchandise-service.csproj","."]
RUN dotnet restore "./merchandise-service.csproj"
COPY . . 
RUN dotnet build "merchandise-service.csproj" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "merchandise-service.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS runtime
WORKDIR /app

EXPOSE 80
EXPOSE 443

FROM runtime as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "merchandise-service.dll"]